import { zodResolver } from '@hookform/resolvers/zod';
import { useForm } from 'react-hook-form';
import { z } from 'zod';
import { Button } from '@/components/ui/Button';
import { Field, Input, Select, Textarea } from '@/components/ui/FormControls';
import { Modal } from '@/components/ui/Modal';
import { hospitalService } from '@/services/hospitalService';
import { useAppStore } from '@/store/useAppStore';
import { useUIStore } from '@/store/useUIStore';
const schema = z.object({ firstName: z.string().min(2), lastName: z.string().min(2), dateOfBirth: z.string().min(1), gender: z.enum(['Female','Male','Non-binary','Prefer not to say']), phone: z.string().min(7), email: z.string().email(), address: z.string().min(5), bloodGroup: z.enum(['A+','A-','B+','B-','AB+','AB-','O+','O-']), allergies: z.string().optional(), conditions: z.string().optional(), insuranceProvider: z.string().min(2), insuranceNumber: z.string().min(3), emergencyContact: z.string().min(3) });
type Form = z.infer<typeof schema>;
export function PatientModal({ open, onClose }: { open: boolean; onClose: () => void }) { const add = useAppStore((state) => state.addPatient); const toast = useUIStore((state) => state.addToast); const form = useForm<Form>({ resolver: zodResolver(schema), defaultValues: { gender: 'Prefer not to say', bloodGroup: 'O+' } }); const submit = async (values: Form) => { const mode = useUIStore.getState().dataMode; const patient = add({ ...values, allergies: values.allergies?.split(',').map((item) => item.trim()).filter(Boolean) ?? [], conditions: values.conditions?.split(',').map((item) => item.trim()).filter(Boolean) ?? [] }); if (mode === 'connected') { try { await hospitalService.savePatient(patient); } catch { useUIStore.getState().setDataMode('offline'); } } toast({ kind: 'success', title: 'Patient registered', description: `${values.firstName} ${values.lastName} is now in the patient directory.` }); form.reset(); onClose(); }; return <Modal open={open} onClose={onClose} title="Register a patient" description="Create a longitudinal patient record and medical context." size="lg" footer={<><Button variant="ghost" onClick={onClose}>Cancel</Button><Button type="submit" form="patient-form">Register patient</Button></>}><form id="patient-form" onSubmit={form.handleSubmit(submit)} className="grid gap-5 sm:grid-cols-2"><Field label="First name"><Input {...form.register('firstName')} /></Field><Field label="Last name"><Input {...form.register('lastName')} /></Field><Field label="Date of birth"><Input type="date" {...form.register('dateOfBirth')} /></Field><Field label="Gender"><Select {...form.register('gender')}><option>Female</option><option>Male</option><option>Non-binary</option><option>Prefer not to say</option></Select></Field><Field label="Phone"><Input {...form.register('phone')} /></Field><Field label="Email"><Input type="email" {...form.register('email')} /></Field><Field label="Address" className="sm:col-span-2"><Input {...form.register('address')} /></Field><Field label="Blood group"><Select {...form.register('bloodGroup')}><option>A+</option><option>A-</option><option>B+</option><option>B-</option><option>AB+</option><option>AB-</option><option>O+</option><option>O-</option></Select></Field><Field label="Insurance provider"><Input {...form.register('insuranceProvider')} /></Field><Field label="Insurance number"><Input {...form.register('insuranceNumber')} /></Field><Field label="Allergies" hint="Separate with commas"><Input {...form.register('allergies')} /></Field><Field label="Conditions" hint="Separate with commas"><Input {...form.register('conditions')} /></Field><Field label="Emergency contact" className="sm:col-span-2"><Textarea {...form.register('emergencyContact')} placeholder="Name · relationship · phone" /></Field></form></Modal>; }
