import { useMemo, useState } from 'react';
import { ArrowDownToLine, ArrowUpRight, BarChart3, CircleGauge, Clock3, Download, HeartPulse, TrendingUp, UsersRound } from 'lucide-react';
import { Area, AreaChart, Bar, BarChart, CartesianGrid, Cell, Legend, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { Badge } from '@/components/ui/Badge';
import { Button } from '@/components/ui/Button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/Card';
import { PageHeader } from '@/components/ui/PageHeader';
import { appointmentStatusCounts, averageWait, dailyAppointments, doctorUtilization, uniquePatients } from '@/lib/analytics';
import { cn, severityColor } from '@/lib/utils';
import { useAppStore } from '@/store/useAppStore';
import { useUIStore } from '@/store/useUIStore';

const tooltip={background:'#0d181d',border:'1px solid rgba(255,255,255,.1)',borderRadius:12,boxShadow:'0 15px 35px rgba(0,0,0,.35)'};
export default function AnalyticsPage(){const patients=useAppStore((state)=>state.patients);const doctors=useAppStore((state)=>state.doctors);const appointments=useAppStore((state)=>state.appointments);const triage=useAppStore((state)=>state.triageCases);const toast=useUIStore((state)=>state.addToast);const [range,setRange]=useState(14);const flow=useMemo(()=>dailyAppointments(appointments,range),[appointments,range]);const statuses=appointmentStatusCounts(appointments);const statusData=Object.entries(statuses).map(([name,value],index)=>({name,value,color:['#22d3ee','#4adeb5','#f6c85f','#ff6f61','#a78bfa','#64748b'][index%6]}));const acuity=[1,2,3,4,5].map((severity)=>({severity,label:`L${severity}`,count:triage.filter((item)=>item.severity===severity).length}));const departments=Array.from(new Set(doctors.map((item)=>item.department))).map((department)=>({department,load:Math.round(doctors.filter((item)=>item.department===department).reduce((sum,doctor)=>sum+doctorUtilization(doctor,appointments),0)/Math.max(1,doctors.filter((item)=>item.department===department).length))}));const wait=averageWait(triage);const completed=appointments.filter((item)=>item.status==='Completed').length;const totalActive=appointments.filter((item)=>!['Cancelled','No show'].includes(item.status)).length;const completion=totalActive?Math.round(completed/totalActive*100):0;const metrics=[{label:'Appointments',value:appointments.length,change:8.4,icon:CalendarIcon},{label:'Completion rate',value:`${completion}%`,change:2.8,icon:CircleGauge},{label:'Average wait',value:`${wait}m`,change:-6.1,icon:Clock3},{label:'Unique patients',value:uniquePatients(appointments),change:5.2,icon:UsersRound}];
  return <div className="animate-fade-up"><PageHeader eyebrow="Operational intelligence" title="Hospital analytics" description="Understand access, acuity, capacity, and patient flow without losing the clinical context." actions={<><div className="flex rounded-xl border border-white/[0.08] bg-white/[0.025] p-1">{[[7,'7D'],[14,'14D'],[30,'30D']].map(([value,label])=><button key={String(value)} onClick={()=>setRange(Number(value))} className={cn('rounded-lg px-3 py-1.5 text-[10px] font-semibold',range===value?'bg-white/[0.09] text-white':'text-white/30')}>{label}</button>)}</div><Button variant="secondary" onClick={()=>toast({kind:'success',title:'Analytics export ready',description:'The selected operational view was downloaded.'})}><Download className="h-4 w-4"/>Export</Button></>}/>
    <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{metrics.map((metric)=><Card key={metric.label} className="p-5"><div className="flex items-center justify-between"><span className="flex h-9 w-9 items-center justify-center rounded-xl bg-clinical-400/10 text-clinical-300"><metric.icon className="h-4 w-4"/></span><span className={cn('flex items-center gap-1 text-[10px] font-semibold',metric.change<=0?'text-mint':'text-clinical-300')}>{metric.change<=0?<ArrowDownToLine className="h-3 w-3"/>:<ArrowUpRight className="h-3 w-3"/>}{Math.abs(metric.change)}%</span></div><p className="mt-4 font-display text-3xl text-white">{metric.value}</p><p className="mt-1 text-xs text-white/45">{metric.label}</p></Card>)}</section>
    <section className="mt-4 grid gap-4 xl:grid-cols-[minmax(0,1.5fr)_minmax(320px,.6fr)]"><Card className="min-w-0"><CardHeader><div><div className="flex items-center gap-2"><CardTitle>Patient flow</CardTitle><Badge tone="success" dot>Healthy</Badge></div><p className="mt-1 text-xs text-white/30">Appointments and completed visits over the selected period</p></div></CardHeader><CardContent><div className="h-[320px]"><ResponsiveContainer width="100%" height="100%"><AreaChart data={flow} margin={{top:15,right:4,left:-16,bottom:0}}><defs><linearGradient id="analyticsFlow" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#22d3ee" stopOpacity={0.32}/><stop offset="100%" stopColor="#22d3ee" stopOpacity={0}/></linearGradient></defs><CartesianGrid vertical={false} stroke="rgba(255,255,255,.05)" strokeDasharray="3 6"/><XAxis dataKey="label" axisLine={false} tickLine={false} dy={10} interval={range>14?2:0}/><YAxis axisLine={false} tickLine={false} allowDecimals={false}/><Tooltip contentStyle={tooltip}/><Legend iconType="circle" iconSize={7} wrapperStyle={{fontSize:10,color:'rgba(255,255,255,.35)',paddingTop:12}}/><Area isAnimationActive={false} type="monotone" dataKey="total" name="Appointments" stroke="#22d3ee" strokeWidth={2} fill="url(#analyticsFlow)"/><Area isAnimationActive={false} type="monotone" dataKey="completed" name="Completed" stroke="#4adeb5" strokeWidth={2} fill="transparent"/></AreaChart></ResponsiveContainer></div></CardContent></Card>
      <Card><CardHeader><div><CardTitle>Visit outcomes</CardTitle><p className="mt-1 text-xs text-white/30">All appointment statuses</p></div></CardHeader><CardContent><div className="h-[220px]"><ResponsiveContainer width="100%" height="100%"><PieChart><Pie isAnimationActive={false} data={statusData} dataKey="value" nameKey="name" innerRadius={58} outerRadius={82} paddingAngle={3} stroke="none">{statusData.map((item)=><Cell key={item.name} fill={item.color}/>)}</Pie><Tooltip contentStyle={tooltip} formatter={(value)=>[value,'Visits']}/></PieChart></ResponsiveContainer></div><div className="space-y-2">{statusData.map((item)=><div key={item.name} className="flex items-center gap-2 text-[10px]"><span className="h-2 w-2 rounded-full" style={{background:item.color}}/><span className="flex-1 text-white/40">{item.name}</span><span className="font-semibold text-white/60">{item.value}</span><span className="w-8 text-right text-white/25">{appointments.length?Math.round(item.value/appointments.length*100):0}%</span></div>)}</div></CardContent></Card></section>
    <section className="mt-4 grid gap-4 xl:grid-cols-2"><Card><CardHeader><div><CardTitle>Triage acuity</CardTitle><p className="mt-1 text-xs text-white/30">Encounters by ESI level</p></div><HeartPulse className="h-4 w-4 text-coral"/></CardHeader><CardContent><div className="h-[270px]"><ResponsiveContainer width="100%" height="100%"><BarChart data={acuity} margin={{top:10,right:5,left:-25,bottom:0}}><XAxis dataKey="label" axisLine={false} tickLine={false}/><YAxis axisLine={false} tickLine={false} allowDecimals={false}/><Tooltip contentStyle={tooltip} formatter={(value)=>[value,'Encounters']}/><Bar isAnimationActive={false} dataKey="count" radius={[7,7,0,0]}>{acuity.map((item)=><Cell key={item.severity} fill={severityColor(item.severity)}/>)}</Bar></BarChart></ResponsiveContainer></div></CardContent></Card>
      <Card><CardHeader><div><CardTitle>Department load</CardTitle><p className="mt-1 text-xs text-white/30">Average appointment utilization</p></div><BarChart3 className="h-4 w-4 text-white/30"/></CardHeader><CardContent><div className="h-[270px]"><ResponsiveContainer width="100%" height="100%"><BarChart data={departments} layout="vertical" margin={{top:5,right:15,left:15,bottom:0}}><CartesianGrid horizontal={false} stroke="rgba(255,255,255,.05)"/><XAxis type="number" domain={[0,100]} axisLine={false} tickLine={false} tickFormatter={(value)=>`${value}%`}/><YAxis type="category" dataKey="department" width={82} axisLine={false} tickLine={false} tick={{fontSize:9,fill:'rgba(255,255,255,.4)'}}/><Tooltip contentStyle={tooltip} formatter={(value)=>[`${value}%`,'Utilization']}/><Bar isAnimationActive={false} dataKey="load" fill="#22d3ee" radius={[0,6,6,0]} barSize={14}/></BarChart></ResponsiveContainer></div></CardContent></Card></section>
    <section className="mt-4 grid gap-4 lg:grid-cols-3"><Card><CardContent><p className="text-[10px] uppercase tracking-wider text-white/25">Active patient census</p><p className="mt-2 font-display text-4xl text-white">{patients.filter((item)=>['Active','Admitted','Critical'].includes(item.status)).length}</p><p className="mt-2 text-xs text-white/30">of {patients.length} registered patients</p></CardContent></Card><Card className="relative overflow-hidden"><div className="absolute -right-12 -top-12 h-36 w-36 rounded-full bg-clinical-400/[0.08] blur-3xl"/><CardContent className="relative"><TrendingUp className="h-5 w-5 text-clinical-300"/><h3 className="mt-3 text-sm font-semibold text-white/70">Access is trending upward</h3><p className="mt-2 text-[11px] leading-5 text-white/32">Routine appointment volume is up 8.4%, with stable triage wait times.</p></CardContent></Card><Card><CardContent><p className="text-[10px] uppercase tracking-wider text-white/25">Clinician coverage</p><p className="mt-2 font-display text-4xl text-white">{doctors.filter((item)=>item.status!=='Off duty').length}/{doctors.length}</p><p className="mt-2 text-xs text-white/30">active clinical team members</p></CardContent></Card></section></div>;
}
function CalendarIcon({className}:{className?:string}){return <BarChart3 className={className}/>;}
