import { useMemo } from 'react';
import { useNavigate } from 'react-router-dom';
import { Activity, ArrowRight, BedDouble, CalendarPlus, CheckCircle2, Clock3, Download, HeartPulse, Plus, Siren, Stethoscope, UserRoundPlus, UsersRound } from 'lucide-react';
import { Area, AreaChart, Bar, BarChart, CartesianGrid, Cell, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { Badge } from '@/components/ui/Badge';
import { Button } from '@/components/ui/Button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/Card';
import { PageHeader } from '@/components/ui/PageHeader';
import { acuityCounts, averageWait, dailyAppointments, todayAppointments } from '@/lib/analytics';
import { cn, formatTime, formatWait, patientName, severityColor, severityLabel, triageSort } from '@/lib/utils';
import { useAppStore } from '@/store/useAppStore';
import { useUIStore } from '@/store/useUIStore';

const tooltip = { background: '#0d181d', border: '1px solid rgba(255,255,255,.1)', borderRadius: 12, boxShadow: '0 15px 35px rgba(0,0,0,.35)' };

export default function DashboardPage() {
  const navigate = useNavigate(); const patients = useAppStore((state) => state.patients); const doctors = useAppStore((state) => state.doctors); const appointments = useAppStore((state) => state.appointments); const triageCases = useAppStore((state) => state.triageCases); const activities = useAppStore((state) => state.activities); const settings = useAppStore((state) => state.settings); const setTriage = useUIStore((state) => state.setTriageModalOpen); const setAppointment = useUIStore((state) => state.setAppointmentModalOpen); const setPatient = useUIStore((state) => state.setPatientModalOpen);
  const today = useMemo(() => todayAppointments(appointments), [appointments]); const waiting = useMemo(() => triageSort(triageCases), [triageCases]); const chart = useMemo(() => dailyAppointments(appointments, 7), [appointments]); const acuity = useMemo(() => acuityCounts(triageCases), [triageCases]); const wait = averageWait(triageCases); const admitted = patients.filter((item) => item.status === 'Admitted' || item.status === 'Critical').length; const completed = today.filter((item) => item.status === 'Completed').length; const activeDoctors = doctors.filter((item) => item.status !== 'Off duty').length;
  const stats = [{ label: "Today's appointments", value: today.length, detail: `${completed} completed`, icon: CalendarPlus, color: 'text-clinical-300' }, { label: 'Waiting in triage', value: waiting.length, detail: wait < 20 ? 'Within target' : `${wait - settings.triageTargetMinutes}m over target`, icon: Siren, color: 'text-coral' }, { label: 'Currently admitted', value: admitted, detail: `${settings.bedCapacity - admitted} beds available`, icon: BedDouble, color: 'text-mint' }, { label: 'Active clinicians', value: activeDoctors, detail: `${doctors.length} on roster`, icon: Stethoscope, color: 'text-violet-300' }];
  return <div className="animate-fade-up"><PageHeader eyebrow="Live clinical operations" title={<>Good morning, Alex. <span className="font-display italic text-clinical-300/90">Here’s the care pulse.</span></>} description={`${settings.hospitalName} · A clear view of today’s access, acuity, and patient flow.`} actions={<><Button variant="secondary" onClick={() => navigate('/reports')}><Download className="h-4 w-4" />Shift report</Button><Button variant="emergency" onClick={() => setTriage(true)}><Siren className="h-4 w-4" />Triage case</Button></>} />
    <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{stats.map((stat) => <Card key={stat.label} className="p-5 transition hover:-translate-y-0.5 hover:border-white/[0.13]"><div className="flex items-start justify-between"><span className={cn('flex h-9 w-9 items-center justify-center rounded-xl border border-white/[0.07] bg-white/[0.035]', stat.color)}><stat.icon className="h-4 w-4" /></span><span className="text-[10px] font-semibold uppercase tracking-wider text-white/25">{stat.detail}</span></div><p className="mt-5 font-display text-[34px] leading-none text-white">{stat.value}</p><p className="mt-2 text-xs font-medium text-white/55">{stat.label}</p></Card>)}</section>
    <section className="mt-4 grid gap-4 xl:grid-cols-[minmax(0,1.55fr)_minmax(330px,.65fr)]"><Card className="min-w-0"><CardHeader><div><div className="flex items-center gap-2"><CardTitle>Patient flow</CardTitle><Badge tone="success" dot>Live</Badge></div><p className="mt-1 text-xs text-white/35">Appointments and completed visits over seven days</p></div><Button variant="secondary" size="sm" onClick={() => setAppointment(true)}><Plus className="h-4 w-4" />Book</Button></CardHeader><CardContent><div className="h-[270px]"><ResponsiveContainer width="100%" height="100%"><AreaChart data={chart} margin={{ top: 15, right: 4, left: -18, bottom: 0 }}><defs><linearGradient id="patientFlow" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#22d3ee" stopOpacity={0.35} /><stop offset="100%" stopColor="#22d3ee" stopOpacity={0} /></linearGradient></defs><CartesianGrid vertical={false} stroke="rgba(255,255,255,.05)" strokeDasharray="3 6" /><XAxis dataKey="label" axisLine={false} tickLine={false} dy={10} /><YAxis axisLine={false} tickLine={false} /><Tooltip contentStyle={tooltip} /><Area isAnimationActive={false} type="monotone" dataKey="total" name="Appointments" stroke="#22d3ee" strokeWidth={2.2} fill="url(#patientFlow)" /></AreaChart></ResponsiveContainer></div></CardContent></Card>
      <Card><CardHeader><div><CardTitle>Triage acuity</CardTitle><p className="mt-1 text-xs text-white/35">Current waiting distribution</p></div><Button variant="ghost" size="icon" onClick={() => navigate('/triage')}><ArrowRight className="h-4 w-4" /></Button></CardHeader><CardContent><div className="h-[180px]"><ResponsiveContainer width="100%" height="100%"><BarChart data={acuity} margin={{ top: 8, right: 4, left: -28, bottom: 0 }}><XAxis dataKey="severity" axisLine={false} tickLine={false} tickFormatter={(value) => `L${value}`} /><YAxis axisLine={false} tickLine={false} allowDecimals={false} /><Tooltip contentStyle={tooltip} formatter={(value) => [value, 'Waiting']} /><Bar isAnimationActive={false} dataKey="count" radius={[6,6,0,0]}>{acuity.map((item) => <Cell key={item.severity} fill={severityColor(item.severity)} />)}</Bar></BarChart></ResponsiveContainer></div><div className="grid grid-cols-5 gap-1">{acuity.map((item) => <div key={item.severity} className="text-center"><p className="text-sm font-semibold text-white/75">{item.count}</p><p className="text-[8px] uppercase tracking-wider text-white/25">L{item.severity}</p></div>)}</div></CardContent></Card></section>
    <section className="mt-4 grid gap-4 xl:grid-cols-[minmax(0,1.45fr)_minmax(330px,.65fr)]"><Card><CardHeader><div><CardTitle>Today’s schedule</CardTitle><p className="mt-1 text-xs text-white/35">Next appointments and care status</p></div><Button variant="ghost" size="sm" onClick={() => navigate('/appointments')}>View calendar <ArrowRight className="h-3.5 w-3.5" /></Button></CardHeader><div className="overflow-x-auto px-3 pb-3"><table className="data-table min-w-[650px]"><thead><tr><th>Time</th><th>Patient</th><th>Clinician</th><th>Type</th><th>Status</th></tr></thead><tbody>{today.slice(0, 7).map((appointment) => { const patient = patients.find((item) => item.id === appointment.patientId); const doctor = doctors.find((item) => item.id === appointment.doctorId); if (!patient || !doctor) return null; return <tr key={appointment.id}><td className="text-xs font-semibold text-white/70">{formatTime(appointment.time)}</td><td><div className="flex items-center gap-2.5"><span className="flex h-8 w-8 items-center justify-center rounded-lg bg-clinical-400/10 text-[9px] font-bold text-clinical-300">{patient.firstName[0]}{patient.lastName[0]}</span><div><p className="text-xs font-semibold text-white/70">{patientName(patient)}</p><p className="text-[9px] text-white/25">{patient.mrn}</p></div></div></td><td className="text-xs text-white/45">{doctor.name}</td><td className="text-xs text-white/40">{appointment.type}</td><td><Badge tone={appointment.status === 'In consultation' ? 'info' : appointment.status === 'Completed' ? 'success' : appointment.status === 'Cancelled' ? 'danger' : 'neutral'} dot>{appointment.status}</Badge></td></tr>; })}</tbody></table></div></Card>
      <Card><CardHeader><div><div className="flex items-center gap-2"><CardTitle>Priority queue</CardTitle><span className="flex h-2 w-2 animate-pulse-soft rounded-full bg-coral" /></div><p className="mt-1 text-xs text-white/35">Triage order by acuity and arrival</p></div><Button size="icon" variant="emergency" onClick={() => setTriage(true)}><Plus className="h-4 w-4" /></Button></CardHeader><CardContent className="space-y-2">{waiting.slice(0, 5).map((item) => { const patient = patients.find((record) => record.id === item.patientId); if (!patient) return null; return <button key={item.id} onClick={() => navigate('/triage')} className="flex w-full items-center gap-3 rounded-xl border border-white/[0.06] bg-white/[0.02] p-3 text-left transition hover:bg-white/[0.04]"><span className="flex h-8 w-8 items-center justify-center rounded-lg text-xs font-extrabold" style={{ backgroundColor: `${severityColor(item.severity)}18`, color: severityColor(item.severity) }}>{item.severity}</span><div className="min-w-0 flex-1"><p className="truncate text-xs font-semibold text-white/70">{patientName(patient)}</p><p className="mt-0.5 truncate text-[10px] text-white/30">{item.complaint}</p></div><div className="text-right"><p className="text-[10px] font-semibold" style={{ color: severityColor(item.severity) }}>{severityLabel(item.severity)}</p><p className="mt-0.5 text-[9px] text-white/25">{formatWait(item.arrivalAt)}</p></div></button>; })}{!waiting.length && <p className="py-10 text-center text-sm text-white/35">No patients waiting.</p>}</CardContent></Card></section>
    <section className="mt-4 grid gap-4 lg:grid-cols-[1fr_1fr]"><Card><CardHeader><div><CardTitle>Recent activity</CardTitle><p className="mt-1 text-xs text-white/35">Care team handoffs and system events</p></div><Activity className="h-4 w-4 text-white/30" /></CardHeader><CardContent className="space-y-1">{activities.slice(0, 5).map((activity, index) => <div key={activity.id} className="relative flex gap-3 pb-4 last:pb-0">{index < 4 && <span className="absolute left-[15px] top-8 h-[calc(100%-24px)] w-px bg-white/[0.07]" />}<span className="z-10 flex h-8 w-8 shrink-0 items-center justify-center rounded-full border border-clinical-400/10 bg-[#101c21] text-clinical-300/70">{activity.type === 'triage' ? <HeartPulse className="h-3.5 w-3.5" /> : activity.type === 'patient' ? <UserRoundPlus className="h-3.5 w-3.5" /> : <CheckCircle2 className="h-3.5 w-3.5" />}</span><div><p className="text-xs font-medium text-white/70">{activity.title}</p><p className="mt-0.5 text-[10px] text-white/30">{activity.description}</p></div></div>)}</CardContent></Card>
      <Card className="relative"><div className="absolute -right-20 -top-20 h-56 w-56 rounded-full bg-clinical-400/[0.08] blur-3xl" /><CardHeader><div><Badge tone="info"><Clock3 className="h-3 w-3" />Handover insight</Badge><CardTitle className="mt-3 text-lg">Protect emergency capacity.</CardTitle></div></CardHeader><CardContent><p className="text-sm leading-6 text-white/42">The current queue has <span className="font-semibold text-white/70">{waiting.filter((item) => item.severity <= 2).length} emergent cases</span> and an average wait of {wait} minutes. Keep one emergency clinician available while routine appointments continue.</p><div className="mt-5 flex gap-2"><Button onClick={() => navigate('/triage')}>Open triage board <ArrowRight className="h-4 w-4" /></Button><Button variant="ghost" onClick={() => setPatient(true)}><UsersRound className="h-4 w-4" />Register patient</Button></div></CardContent></Card></section>
  </div>;
}
