import { useMemo, useState } from 'react';
import { zodResolver } from '@hookform/resolvers/zod';
import { useForm } from 'react-hook-form';
import { z } from 'zod';
import { Award, CalendarDays, CheckCircle2, Clock3, Mail, Phone, Plus, Star, Stethoscope } from 'lucide-react';
import { Badge } from '@/components/ui/Badge';
import { Button } from '@/components/ui/Button';
import { Card } from '@/components/ui/Card';
import { Field, Input } from '@/components/ui/FormControls';
import { Modal } from '@/components/ui/Modal';
import { PageHeader } from '@/components/ui/PageHeader';
import { doctorUtilization } from '@/lib/analytics';
import { cn, dateKey, formatTime, patientName } from '@/lib/utils';
import { hospitalService } from '@/services/hospitalService';
import { useAppStore } from '@/store/useAppStore';
import { useUIStore } from '@/store/useUIStore';
import type { Doctor, DoctorStatus } from '@/types';

const statusTone:Record<DoctorStatus,'success'|'danger'|'warning'|'neutral'>={Available:'success','In surgery':'danger','On call':'warning','Off duty':'neutral'};
const schema=z.object({name:z.string().min(4),specialization:z.string().min(2),department:z.string().min(2),email:z.string().email(),phone:z.string().min(7)});type Form=z.infer<typeof schema>;
function AddDoctor({open,onClose}:{open:boolean;onClose:()=>void}){const add=useAppStore((state)=>state.addDoctor);const toast=useUIStore((state)=>state.addToast);const form=useForm<Form>({resolver:zodResolver(schema)});const submit=async(values:Form)=>{const mode=useUIStore.getState().dataMode;const doctor=add(values);if(mode==='connected'){try{await hospitalService.saveDoctor(doctor);}catch{useUIStore.getState().setDataMode('offline');}}toast({kind:'success',title:'Clinician added',description:`${values.name} is now on the roster.`});form.reset();onClose();};return <Modal open={open} onClose={onClose} title="Add a clinician" description="Create a care-team profile and department assignment." footer={<><Button variant="ghost" onClick={onClose}>Cancel</Button><Button type="submit" form="doctor-form">Add clinician</Button></>}><form id="doctor-form" onSubmit={form.handleSubmit(submit)} className="grid gap-5 sm:grid-cols-2"><Field label="Full name" className="sm:col-span-2"><Input {...form.register('name')} placeholder="Dr. Jordan Lee"/></Field><Field label="Specialization"><Input {...form.register('specialization')} placeholder="Cardiology"/></Field><Field label="Department"><Input {...form.register('department')} placeholder="Cardiology"/></Field><Field label="Email"><Input type="email" {...form.register('email')}/></Field><Field label="Phone"><Input {...form.register('phone')}/></Field></form></Modal>}

export default function DoctorsPage(){const doctors=useAppStore((state)=>state.doctors);const appointments=useAppStore((state)=>state.appointments);const patients=useAppStore((state)=>state.patients);const addToast=useUIStore((state)=>state.addToast);const [open,setOpen]=useState(false);const [department,setDepartment]=useState('All');const [selected,setSelected]=useState<Doctor|null>(null);const departments=Array.from(new Set(doctors.map((item)=>item.department)));const filtered=doctors.filter((item)=>department==='All'||item.department===department);const scheduleDays=useMemo(()=>Array.from({length:7},(_,index)=>{const date=new Date();date.setDate(date.getDate()+index);return dateKey(date);}),[]);const today=scheduleDays[0];
  return <div className="animate-fade-up"><PageHeader eyebrow="Clinical coverage" title="Clinical team" description="Balance clinician capacity, specialist expertise, and patient demand across the week." actions={<Button onClick={()=>setOpen(true)}><Plus className="h-4 w-4"/>Add clinician</Button>}/>
    <section className="mb-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{[{label:'Active clinicians',value:doctors.filter((item)=>item.status!=='Off duty').length,detail:`${doctors.length} total roster`,icon:Stethoscope},{label:'Available now',value:doctors.filter((item)=>item.status==='Available').length,detail:'Ready for patients',icon:CheckCircle2},{label:'On call',value:doctors.filter((item)=>item.status==='On call').length,detail:'Escalation coverage',icon:Phone},{label:'Average rating',value:(doctors.reduce((sum,item)=>sum+item.rating,0)/doctors.length).toFixed(1),detail:'Patient experience',icon:Star}].map((stat)=><Card key={stat.label} className="flex items-center gap-4 p-4 sm:p-5"><span className="flex h-10 w-10 items-center justify-center rounded-xl border border-clinical-400/10 bg-clinical-400/[0.07] text-clinical-300"><stat.icon className="h-[18px] w-[18px]"/></span><div><p className="text-lg font-semibold text-white">{stat.value}</p><p className="text-xs font-medium text-white/50">{stat.label}</p><p className="text-[10px] text-white/25">{stat.detail}</p></div></Card>)}</section>
    <div className="mb-4 flex gap-2 overflow-x-auto pb-1">{['All',...departments].map((item)=><button key={item} onClick={()=>setDepartment(item)} className={cn('whitespace-nowrap rounded-full border px-3.5 py-2 text-xs font-medium transition',department===item?'border-clinical-400/25 bg-clinical-400/10 text-clinical-300':'border-white/[0.07] bg-white/[0.025] text-white/35')}>{item}</button>)}</div>
    <section className="grid gap-4 md:grid-cols-2 2xl:grid-cols-4">{filtered.map((doctor)=>{const utilization=doctorUtilization(doctor,appointments);const next=appointments.filter((item)=>item.doctorId===doctor.id&&item.date>=today&&!['Cancelled','Completed','No show'].includes(item.status)).sort((a,b)=>`${a.date}${a.time}`.localeCompare(`${b.date}${b.time}`))[0];return <Card key={doctor.id} className="group cursor-pointer transition duration-300 hover:-translate-y-1 hover:border-white/[0.13]" onClick={()=>setSelected(doctor)}><div className="relative h-1.5" style={{background:`linear-gradient(90deg,${doctor.color},transparent)`}}/><div className="p-5"><div className="flex items-start justify-between"><span className="flex h-12 w-12 items-center justify-center rounded-2xl text-sm font-extrabold text-[#061014]" style={{background:doctor.color}}>{doctor.name.split(' ').slice(1).map((part)=>part[0]).join('')}</span><Badge tone={statusTone[doctor.status]} dot>{doctor.status}</Badge></div><h2 className="mt-4 text-base font-semibold text-white/80">{doctor.name}</h2><p className="mt-1 text-xs text-white/35">{doctor.specialization} · {doctor.department}</p><div className="mt-4 flex items-center gap-4 text-[10px] text-white/30"><span className="flex items-center gap-1"><Star className="h-3.5 w-3.5 text-amber-200"/>{doctor.rating}</span><span className="flex items-center gap-1"><Award className="h-3.5 w-3.5"/>{doctor.experienceYears} years</span></div><div className="mt-5"><div className="mb-1.5 flex justify-between text-[10px]"><span className="text-white/30">Today’s utilization</span><span className="font-semibold text-white/60">{utilization}%</span></div><div className="h-1.5 overflow-hidden rounded-full bg-white/[0.055]"><div className="h-full rounded-full" style={{width:`${utilization}%`,background:doctor.color}}/></div></div><div className="mt-4 flex items-center gap-2 border-t border-white/[0.055] pt-4 text-[10px] text-white/30"><Clock3 className="h-3.5 w-3.5"/>Next: <span className="text-white/55">{next?`${next.date===today?'Today':next.date.slice(5)} · ${formatTime(next.time)}`:'No upcoming visits'}</span></div></div></Card>})}</section>
    <Card className="mt-4"><div className="p-5 sm:p-6"><div className="flex items-center justify-between"><div><h2 className="text-base font-semibold text-white">Weekly schedule</h2><p className="mt-1 text-xs text-white/30">Appointment load across the clinical team</p></div><CalendarDays className="h-4 w-4 text-white/30"/></div><div className="mt-5 overflow-x-auto"><table className="w-full min-w-[820px] text-left text-xs"><thead><tr className="border-b border-white/[0.06]">{scheduleDays.map((date)=><th key={date} className="px-3 pb-3 text-[9px] font-semibold uppercase tracking-wider text-white/25">{new Intl.DateTimeFormat('en-US',{weekday:'short',month:'short',day:'numeric'}).format(new Date(`${date}T12:00:00`))}</th>)}</tr></thead><tbody>{doctors.map((doctor)=><tr key={doctor.id} className="border-b border-white/[0.045] last:border-0"><td className="px-3 py-3"><div className="flex items-center gap-2"><span className="h-7 w-1 rounded-full" style={{background:doctor.color}}/><div><p className="text-xs font-medium text-white/60">{doctor.name}</p><p className="text-[9px] text-white/25">{doctor.specialization}</p></div></div></td>{scheduleDays.map((date)=>{const count=appointments.filter((item)=>item.doctorId===doctor.id&&item.date===date&&!['Cancelled','No show'].includes(item.status)).length;return <td key={date} className="px-3 py-3"><div className={cn('flex h-8 min-w-14 items-center justify-center rounded-lg text-[10px] font-semibold',count?'bg-clinical-400/[0.08] text-clinical-300':'bg-white/[0.02] text-white/15')}>{count||'–'}</div></td>})}</tr>)}</tbody></table></div></div></Card>
    <AddDoctor open={open} onClose={()=>setOpen(false)}/>{selected&&<Modal open onClose={()=>setSelected(null)} title={selected.name} description={`${selected.specialization} · ${selected.department}`} footer={<Button onClick={()=>{setSelected(null);addToast({kind:'info',title:'Schedule opened',description:'Detailed slot management is ready for integration.'})}}>View full schedule</Button>}><div className="text-center"><span className="mx-auto flex h-20 w-20 items-center justify-center rounded-2xl text-xl font-extrabold text-[#061014]" style={{background:selected.color}}>{selected.name.split(' ').slice(1).map((part)=>part[0]).join('')}</span><div className="mt-4 flex justify-center"><Badge tone={statusTone[selected.status]} dot>{selected.status}</Badge></div><div className="mt-6 grid grid-cols-3 gap-2">{[['Patients today',selected.patientsToday],['Rating',selected.rating],['Experience',`${selected.experienceYears} yrs`]].map(([label,value])=><div key={label} className="rounded-xl border border-white/[0.06] p-3"><p className="text-[9px] uppercase tracking-wider text-white/25">{label}</p><p className="mt-1 text-sm font-semibold text-white/70">{value}</p></div>)}</div><div className="mt-5 space-y-2 rounded-xl border border-white/[0.06] p-4 text-xs text-white/40"><p className="flex items-center gap-2"><Mail className="h-4 w-4 text-white/25"/>{selected.email}</p><p className="flex items-center gap-2"><Phone className="h-4 w-4 text-white/25"/>{selected.phone}</p></div><p className="mt-4 text-[10px] text-white/25">Today’s patient list: {appointments.filter((item)=>item.doctorId===selected.id&&item.date===today).map((item)=>patientName(patients.find((patient)=>patient.id===item.patientId)!)).join(', ')||'No appointments'}</p></div></Modal>}</div>;
}
