import { lazy, Suspense } from 'react';
import { BrowserRouter, Route, Routes } from 'react-router-dom';
import { ArrowLeft, HeartPulse } from 'lucide-react';
import { AppShell } from '@/components/layout/AppShell';
import { Button } from '@/components/ui/Button';
import { ToastRegion } from '@/components/ui/ToastRegion';
import { useBackendSync } from '@/hooks/useBackendSync';
const DashboardPage=lazy(()=>import('@/pages/DashboardPage'));const PatientsPage=lazy(()=>import('@/pages/PatientsPage'));const AppointmentsPage=lazy(()=>import('@/pages/AppointmentsPage'));const TriagePage=lazy(()=>import('@/pages/TriagePage'));const DoctorsPage=lazy(()=>import('@/pages/DoctorsPage'));const AnalyticsPage=lazy(()=>import('@/pages/AnalyticsPage'));const ReportsPage=lazy(()=>import('@/pages/ReportsPage'));const SettingsPage=lazy(()=>import('@/pages/SettingsPage'));
function Loader(){return <div className="space-y-4" role="status"><div className="h-8 w-56 animate-pulse rounded-lg bg-white/[0.05]"/><div className="h-4 w-96 max-w-full animate-pulse rounded bg-white/[0.03]"/><div className="grid gap-3 pt-5 sm:grid-cols-2 xl:grid-cols-4">{[0,1,2,3].map((item)=><div key={item} className="h-32 animate-pulse rounded-2xl border border-white/[0.05] bg-white/[0.025]"/>)}</div></div>}
function NotFound(){return <div className="flex min-h-[70vh] flex-col items-center justify-center text-center"><span className="flex h-16 w-16 items-center justify-center rounded-2xl border border-clinical-400/15 bg-clinical-400/[0.06] text-clinical-300"><HeartPulse className="h-7 w-7"/></span><p className="eyebrow mt-6">404 · Workspace not found</p><h1 className="mt-2 font-display text-5xl text-white">Let’s return to care.</h1><p className="mt-3 text-sm text-white/38">The requested clinical workspace does not exist.</p><a href="/" className="mt-6"><Button><ArrowLeft className="h-4 w-4"/>Back to overview</Button></a></div>}
export default function App(){useBackendSync();return <BrowserRouter><Suspense fallback={<Loader/>}><Routes><Route element={<AppShell/>}><Route index element={<DashboardPage/>}/><Route path="patients" element={<PatientsPage/>}/><Route path="appointments" element={<AppointmentsPage/>}/><Route path="triage" element={<TriagePage/>}/><Route path="doctors" element={<DoctorsPage/>}/><Route path="analytics" element={<AnalyticsPage/>}/><Route path="reports" element={<ReportsPage/>}/><Route path="settings" element={<SettingsPage/>}/><Route path="*" element={<NotFound/>}/></Route></Routes></Suspense><ToastRegion/></BrowserRouter>}
